### ISSUE TITLE
Allow multiple ORIGINs in a single zone file

### ISSUE THREAD

**Issue by hax0rbana-adam** [msterhuj/ansible-role-bind9#9]
# Problem

In #8 I mentioned an example configuration which had two origins (example.com and test.example.com). This is only possible in the current code via a gnarly hack.

The desired configuration file would look something like the snippet below:

```
ns1                     IN      A       192.168.1.100
www                     IN      A       192.168.1.120

$ORIGIN test.example.com.
ns1                     IN      A       192.168.2.100
www                     IN      A       192.168.2.120
```

That `$ORIGIN` can currently only be accomplished with a record like this:

```yaml
  - name: '$ORIGIN test.example.com. ; Hack to change origin'
    type: ''
    value: ''
```

It works, but... yuck.

# Solution

My proposed solution is to look for an `origin` key in the dictionary and if it exists, just output that. If the key is missing, it'll fall back to what it does now (creating the record with the name/type/value). The bind9_zones is already a list, which means the order will be guaranteed, so this should work nicely.

This would make the `records` key of the `bind9_zones` variable look something like this:

```yaml
records:
  - name: 'ns1'
    type: 'A'
    value: '192.168.1.100'
  - name: 'www'
    type: 'A'
    value: '192.168.1.120'
  - origin: '$ORIGIN test.example.com.'
  - name: 'ns1'
    type: 'A'
    value: '192.168.2.100'
  - name: 'www'
    type: 'A'
    value: '192.168.2.120'
```
